---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts/{post_id}/comments":
    parameters:
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      tags:
      - Comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
  "/api/v1/posts/{post_id}/comments/{id}":
    parameters:
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
    put:
      summary: update comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
    delete:
      summary: delete comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
  "/api/v1/posts":
    get:
      summary: list posts
      tags:
      - Posts
      responses:
        '200':
          description: successful
    post:
      summary: create post
      tags:
      - Posts
      responses:
        '200':
          description: successful
  "/api/v1/posts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show post
      tags:
      - Posts
      responses:
        '200':
          description: successful
    patch:
      summary: update post
      tags:
      - Posts
      responses:
        '200':
          description: successful
    put:
      summary: update post
      tags:
      - Posts
      responses:
        '200':
          description: successful
    delete:
      summary: delete post
      tags:
      - Posts
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
