---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts/{post_id}/comments":
    parameters:
    - name: post_id
      in: path
      default: 1
      description: Post ID
      required: true
      schema:
        type: integer
    get:
      summary: list comments
      parameters:
      - name: status
        in: query
        description: 'Filter comments by status: published/unpublished'
        schema:
          type: string
      tags:
      - Comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: created
        '400':
          description: bad request
        '422':
          description: unprocessable entity
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
                  default: 1
                post_id:
                  type: integer
                  default: 1
              required:
              - body
              - status
              - author_id
              - post_id
  "/api/v1/posts/{post_id}/comments/{id}":
    parameters:
    - name: post_id
      in: path
      default: 1
      description: Post ID
      required: true
      schema:
        type: integer
    - name: id
      in: path
      description: ID of the required comment
      required: true
      schema:
        type: integer
    get:
      summary: show comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
        '404':
          description: not found
    patch:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad request
        '404':
          description: not found
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
                  default: 1
                post_id:
                  type: integer
                  default: 1
              required:
              - body
              - status
              - author_id
              - post_id
    put:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad request
        '404':
          description: not found
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
                  default: 1
                post_id:
                  type: integer
                  default: 1
              required:
              - body
              - status
              - author_id
              - post_id
    delete:
      summary: delete comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
        '400':
          description: bad request
        '404':
          description: not found
  "/api/v1/posts":
    get:
      summary: list posts
      tags:
      - Posts
      parameters:
      - name: search
        in: query
        description: Search posts by keywords from title or body
        schema:
          type: string
      - name: status
        in: query
        description: 'Filter posts by status: published/unpublished'
        schema:
          type: string
      - name: author
        in: query
        description: Filter posts by author name
        schema:
          type: string
      - name: tags
        in: query
        description: Filter posts by tags
        schema:
          type: string
      - name: sort
        in: query
        description: 'Sort posts by titles: asc/desc'
        schema:
          type: string
      - name: page
        in: query
        description: Choose page
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '500':
          description: internal server error
    post:
      summary: create post
      tags:
      - Posts
      parameters: []
      responses:
        '201':
          description: created
        '400':
          description: bad request
        '422':
          description: unprocessable entity
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  default: unpublished
                author_id:
                  type: integer
                  default: 1
              required:
              - title
              - body
              - status
              - author_id
  "/api/v1/posts/{id}":
    parameters:
    - name: id
      in: path
      description: ID of the required post
      required: true
      schema:
        type: integer
    get:
      summary: show post
      tags:
      - Posts
      responses:
        '200':
          description: successful
        '404':
          description: not found
    patch:
      summary: update post
      tags:
      - Posts
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad request
        '404':
          description: not found
        '422':
          description: unprocessable entity
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  default: unpublished
                author_id:
                  type: integer
                  default: 1
              required:
              - title
              - body
              - status
              - author_id
    put:
      summary: update post
      parameters: []
      tags:
      - Posts
      responses:
        '200':
          description: successful
        '400':
          description: bad request
        '404':
          description: not found
        '422':
          description: unprocessable entity
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  default: unpublished
                author_id:
                  type: integer
                  default: 1
              required:
              - title
              - body
              - status
              - author_id
    delete:
      summary: delete post
      tags:
      - Posts
      responses:
        '200':
          description: successful
        '400':
          description: bad request
        '404':
          description: not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
